<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 ' . $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>
        <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0">
        <meta name="author" content="Josh Stuart">
        <meta name="author" content="Tim Roediger">
        
        <link rel="shortcut icon" type="image/png" href="/images/favicon.png">

        <link href="https://fonts.googleapis.com/css?family=Yanone+Kaffeesatz:400,300,700" rel="stylesheet" type="text/css">
        
        <?php
        echo $this->plugin('HeadLink');
        echo $this->plugin('HeadStyle');
        echo $this->plugin('HeadScript');
        ?>
    </head>
    <body>
        <div class="navbar">
            <div class="navbar-inner">
                <div class="container-fluid">
                    <button data-target=".nav-collapse" data-toggle="collapse" class="btn btn-navbar" type="button">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a href="/admin/" class="brand"><img src="/assets/images/general/logo-header.png"></a>
                </div>
            </div>
        </div>
        <div id="content" class="container-fluid">
            <?php echo $this->content; ?>
        </div>

        <?= $this->plugin('InlineScript') ?>
    </body>
</html>
