<div class="row-fluid pod-container">
    <div class="login pod">
        <div class="well">
            <form action="/admin/" method="post">
                <h2>Log into your store</h2>
                <div class="row-fluid">
                    <div class="control-group">
                        <label for="loginEmail" class="control-label">Email<span class="text-warning"> *</span></label>
                        <div class="controls">
                            <input id="loginEmail" name="email" class="span8" placeholder="Enter your email address" type="text">
                        </div>
                    </div>
                    <div class="control-group">
                        <label for="loginPassword" class="control-label">Password<span class="text-warning"> *</span></label>
                        <div class="controls">
                            <input id="loginPassword" name="password" class="span8" placeholder="Enter your password" type="password">
                            <small><a href='/admin/forgot-password'>Forgot your password?</a></small>
                        </div>
                    </div>
                    <div class="control-group">
                        <div class="row-fluid">
                            <div class="span8">
                                <button class="btn btn-primary pull-right" type="submit">Log in</button>
                                <input name="submitted" value="true" type="hidden">
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
        <div class="footer">
            New to Zoop? <a href="http://zoopcommerce.com">Sign up for free</a>.
        </div>
    </div>
</div>